name: buildimage

on:
  workflow_run:
    workflows: [codequality]
    types:
      - completed

env:
  IMAGE_TAG: latest

jobs:
  build-and-push-backend-do:
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: |
          cd build ;\
          docker buildx build --load -f Dockerfile  \
            -t registry.digitalocean.com/aeroklubostrowski/planereservation:app-1.0 \
            --target prod-app ./.. ;\

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/aeroklubostrowski/planereservation:app-1.0
