name: buildimage

on:
  workflow_run:
    workflows: [codequality]
    types:
      - completed

env:
  IMAGE_TAG: latest

jobs:
  build-and-push-backend-do:
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
 
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Build image
        run: |
          cd build ;\
          docker build --load -f Dockerfile  \
            -t local.system:latest . ;\
          docker image ls ;\
          docker build --load -f app.Dockerfile  \
            -t registry.digitalocean.com/aeroklubostrowski/planereservation:app-1.0 \
            --build-arg SOURCE_SYSTEM_IMAGE=local.system:latest \
            --target prod ./.. ;

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/aeroklubostrowski/planereservation:app-1.0
