name: buildimage

on:
  workflow_run:
    workflows: [codequality]
    types:
      - completed

env:
  IMAGE_TAG: latest

jobs:
  testwm:
    runs-on: ubuntu-latest

    # see https://github.com/shivammathur/setup-php for more information
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.3'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Execute php cs
      run: ./vendor/bin/ecs check ./app ./tests --config ecs.php
